In [3]:
#model: using the FinancialBERT model, which is fine-tuned on financial news data and suitable for my subject
from transformers import BertTokenizer, BertForSequenceClassification
from transformers import pipeline
import transformers
import pandas as pd
import numpy as np

d:\self-definedEnvrionments\pytorch_test\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
print(transformers.__version__)

4.51.3

In [5]:
model = BertForSequenceClassification.from_pretrained("ahmedrachid/FinancialBERT-Sentiment-Analysis",num_labels=3)
tokenizer = BertTokenizer.from_pretrained("ahmedrachid/FinancialBERT-Sentiment-Analysis")

nlp = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer)

Device set to use cpu

In [ ]:
#import data
train = pd.read_csv(r"G:\Interview Projects\reddit\trainingdata.csv")
train

,id,title,selftext,author,created_utc,score,num_comments,url,subreddit,upvote_ratio,...,dltt_be,de_ratio,quick_ratio,cash_conversion,inv_turn,rect_turn,sale_invcap,sale_equity,sale_nwc,TICKER
0,nphciu,Which one of you is it?,NaN,Cindersash,1622507119,1,1.0,https://i.imgur.com/eYiuTBo.jpg,wallstreetbets,1.00,...,2.614,5.957,0.735,106.183,NaN,3.723,1.120,4.173,NaN,IT
1,npjoel,Housing (2007 again?),Just curious about what the apes think about t...,Albino_Whale,1622514846,2659,2392.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.93,...,2.614,5.957,0.735,106.183,NaN,3.723,1.120,4.173,NaN,IT
2,npl5qc,I was wondering this is a good investment with...,NaN,sebas942805,1622519887,1,0.0,https://i.redd.it/ltceazx4vk271.jpg,wallstreetbets,1.00,...,2.614,5.957,0.735,106.183,NaN,3.723,1.120,4.173,NaN,IT
3,npmj2m,"Is Such positive P&amp;L possible on AMC , can...",NaN,Only4you-1331,1622524975,1,0.0,https://i.redd.it/s6g709fx9l271.png,wallstreetbets,1.00,...,2.614,5.957,0.735,106.183,NaN,3.723,1.120,4.173,NaN,IT
4,npmxd9,Bright minds… every time I read these kind of ...,NaN,ExpressionNaive1923,1622526579,1,0.0,https://finance.yahoo.com/news/strange-gamesto...,wallstreetbets,1.00,...,2.614,5.957,0.735,106.183,NaN,3.723,1.120,4.173,NaN,IT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44058,p770zf,Yolo’d apple calls for 8/20(First post on WSB ...,NaN,theboyfromcali,1629344029,1,0.0,https://www.reddit.com/gallery/p770zf,wallstreetbets,1.00,...,1.273,2.021,0.929,3.324,15.491,10.253,0.481,1.189,-109.900,TMUS
44059,p7pqpp,ALL IN PAYSAFE,I saw alot of DD on Paysafe that got me intere...,Curious-Interest-734,1629413907,129,62.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.90,...,0.293,0.614,1.086,16.409,NaN,9.301,0.207,0.275,20.279,GPN
44060,paami8,Why Upstart Will Make You a Millionaire.. in 5...,"Ok, maybe not a millionaire, but the upside po...",ctrlinvest,1629758443,224,195.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.82,...,1.452,2.664,1.278,43.759,NaN,3.084,0.801,1.998,10.124,MMC
44061,pdv0na,"Hurricane Ida is ""Worst in 170 Years"" How to B...",Okay fellow apes.\n\nHurricane Ida is mere hou...,CaspeanSea,1630242870,9536,1797.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.82,...,1.572,3.103,0.914,19.852,32.546,6.612,0.605,1.950,67.165,URI
44062,pdyttq,How to bag hold this hurricane like an Ape Kin...,"First off, what the fuck kind of crack are you...",brbcripwalking,1630255684,2222,277.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.94,...,1.572,3.103,0.914,19.852,32.546,6.612,0.605,1.950,67.165,URI

In [7]:
test = train['title'][train['title'].isna()==False].to_list() #title has more valid data
type(test)

list

In [28]:
results = nlp(test)
results

[{'label': 'neutral', 'score': 0.9902744293212891},
 {'label': 'neutral', 'score': 0.9995539784431458},
 {'label': 'neutral', 'score': 0.9996733665466309},
 {'label': 'neutral', 'score': 0.9860697984695435},
 {'label': 'neutral', 'score': 0.9993417859077454},
 {'label': 'neutral', 'score': 0.7778757214546204},
 {'label': 'neutral', 'score': 0.9995920062065125},
 {'label': 'neutral', 'score': 0.9992361068725586},
 {'label': 'neutral', 'score': 0.99950110912323},
 {'label': 'positive', 'score': 0.9997647404670715},
 {'label': 'positive', 'score': 0.9968352913856506},
 {'label': 'neutral', 'score': 0.999173104763031},
 {'label': 'neutral', 'score': 0.99972003698349},
 {'label': 'positive', 'score': 0.9964268803596497},
 {'label': 'neutral', 'score': 0.9995864033699036},
 {'label': 'neutral', 'score': 0.9996517896652222},
 {'label': 'neutral', 'score': 0.9995408058166504},
 {'label': 'neutral', 'score': 0.9975849390029907},
 {'label': 'neutral', 'score': 0.9991903901100159},
 {'label': 'neutral', 'score': 0.9666111469268799},
 {'label': 'neutral', 'score': 0.9666111469268799},
 {'label': 'neutral', 'score': 0.9955618381500244},
 {'label': 'positive', 'score': 0.9871881008148193},
 {'label': 'neutral', 'score': 0.9950292706489563},
 {'label': 'positive', 'score': 0.9998263716697693},
 {'label': 'neutral', 'score': 0.9997038245201111},
 {'label': 'neutral', 'score': 0.995535135269165},
 {'label': 'neutral', 'score': 0.9997043013572693},
 {'label': 'neutral', 'score': 0.9997748732566833},
 {'label': 'positive', 'score': 0.999717652797699},
 {'label': 'neutral', 'score': 0.9994964599609375},
 {'label': 'neutral', 'score': 0.9991084933280945},
 {'label': 'neutral', 'score': 0.9941533207893372},
 {'label': 'neutral', 'score': 0.9991806149482727},
 {'label': 'neutral', 'score': 0.9974493384361267},
 {'label': 'neutral', 'score': 0.9997113347053528},
 {'label': 'neutral', 'score': 0.9996451139450073},
 {'label': 'positive', 'score': 0.9998094439506531},
 {'label': 'neutral', 'score': 0.9996927976608276},
 {'label': 'positive', 'score': 0.9988681077957153},
 {'label': 'neutral', 'score': 0.9994623064994812},
 {'label': 'neutral', 'score': 0.9809807538986206},
 {'label': 'neutral', 'score': 0.9993034601211548},
 {'label': 'neutral', 'score': 0.9982119798660278},
 {'label': 'neutral', 'score': 0.9990859031677246},
 {'label': 'positive', 'score': 0.9955981373786926},
 {'label': 'neutral', 'score': 0.9986624717712402},
 {'label': 'positive', 'score': 0.9918364882469177},
 {'label': 'neutral', 'score': 0.9996888637542725},
 {'label': 'neutral', 'score': 0.9962244033813477},
 {'label': 'neutral', 'score': 0.940775454044342},
 {'label': 'neutral', 'score': 0.9988279938697815},
 {'label': 'neutral', 'score': 0.999622106552124},
 {'label': 'neutral', 'score': 0.9996824264526367},
 {'label': 'neutral', 'score': 0.9996080994606018},
 {'label': 'neutral', 'score': 0.5233191847801208},
 {'label': 'neutral', 'score': 0.9998089671134949},
 {'label': 'neutral', 'score': 0.999249279499054},
 {'label': 'neutral', 'score': 0.9990605711936951},
 {'label': 'neutral', 'score': 0.9995864033699036},
 {'label': 'neutral', 'score': 0.9942171573638916},
 {'label': 'neutral', 'score': 0.8751985430717468},
 {'label': 'neutral', 'score': 0.9399141669273376},
 {'label': 'negative', 'score': 0.9673168063163757},
 {'label': 'neutral', 'score': 0.9987664222717285},
 {'label': 'neutral', 'score': 0.9996157884597778},
 {'label': 'neutral', 'score': 0.9977551102638245},
 {'label': 'neutral', 'score': 0.9987422823905945},
 {'label': 'neutral', 'score': 0.9996689558029175},
 {'label': 'neutral', 'score': 0.9991961121559143},
 {'label': 'neutral', 'score': 0.9995731711387634},
 {'label': 'positive', 'score': 0.5706626772880554},
 {'label': 'neutral', 'score': 0.9993630051612854},
 {'label': 'neutral', 'score': 0.9994481205940247},
 {'label': 'neutral', 'score': 0.9949684739112854},
 {'label': 'neutral', 'score': 0.999660849571228},
 {'label': 'neutral', 'score': 0.9985848665237427},
 {'label': 'neutral', 'score': 0.9984801411628723},
 {'label': 'neutral', 'score': 0.9987508058547974},
 {'label': 'neutral', 'score': 0.9812784790992737},
 {'label': 'negative', 'score': 0.7783216238021851},
 {'label': 'neutral', 'score': 0.9964694976806641},
 {'label': 'neutral', 'score': 0.5119136571884155},
 {'label': 'neutral', 'score': 0.9994394183158875},
 {'label': 'neutral', 'score': 0.9995055198669434},
 {'label': 'neutral', 'score': 0.9995577931404114},
 {'label': 'neutral', 'score': 0.999538779258728},
 {'label': 'neutral', 'score': 0.9995759129524231},
 {'label': 'neutral', 'score': 0.9994069337844849},
 {'label': 'neutral', 'score': 0.9994691014289856},
 {'label': 'neutral', 'score': 0.9973590970039368},
 {'label': 'neutral', 'score': 0.9990687966346741},
 {'label': 'neutral', 'score': 0.9937187433242798},
 {'label': 'positive', 'score': 0.9992782473564148},
 {'label': 'neutral', 'score': 0.9997499585151672},
 {'label': 'neutral', 'score': 0.9996713399887085},
 {'label': 'neutral', 'score': 0.9993901252746582},
 {'label': 'neutral', 'score': 0.9995529055595398},
 {'label': 'positive', 'score': 0.9971285462379456},
 {'label': 'neutral', 'score': 0.9996968507766724},
 {'label': 'positive', 'score': 0.9968110918998718},
 {'label': 'neutral', 'score': 0.9994238615036011},
 {'label': 'positive', 'score': 0.9610344171524048},
 {'label': 'neutral', 'score': 0.9995108842849731},
 {'label': 'neutral', 'score': 0.9954364895820618},
 {'label': 'neutral', 'score': 0.9997178912162781},
 {'label': 'neutral', 'score': 0.9986867308616638},
 {'label': 'neutral', 'score': 0.9996494054794312},
 {'label': 'neutral', 'score': 0.9997598528862},
 {'label': 'neutral', 'score': 0.9997088313102722},
 {'label': 'neutral', 'score': 0.9995439648628235},
 {'label': 'neutral', 'score': 0.9997178912162781},
 {'label': 'neutral', 'score': 0.9997615218162537},
 {'label': 'neutral', 'score': 0.850580632686615},
 {'label': 'neutral', 'score': 0.9996639490127563},
 {'label': 'neutral', 'score': 0.9994226694107056},
 {'label': 'neutral', 'score': 0.9997497200965881},
 {'label': 'neutral', 'score': 0.9994226694107056},
 {'label': 'neutral', 'score': 0.9994049072265625},
 {'label': 'neutral', 'score': 0.9995537400245667},
 {'label': 'neutral', 'score': 0.9988970756530762},
 {'label': 'neutral', 'score': 0.9987736344337463},
 {'label': 'neutral', 'score': 0.9995914101600647},
 {'label': 'neutral', 'score': 0.9996702671051025},
 {'label': 'neutral', 'score': 0.9997637867927551},
 {'label': 'neutral', 'score': 0.9993789196014404},
 {'label': 'neutral', 'score': 0.999174177646637},
 {'label': 'neutral', 'score': 0.9992654919624329},
 {'label': 'neutral', 'score': 0.9983717799186707},
 {'label': 'neutral', 'score': 0.9992328882217407},
 {'label': 'negative', 'score': 0.9137769937515259},
 {'label': 'neutral', 'score': 0.999785840511322},
 {'label': 'neutral', 'score': 0.9996931552886963},
 {'label': 'positive', 'score': 0.9955525994300842},
 {'label': 'neutral', 'score': 0.9986901879310608},
 {'label': 'neutral', 'score': 0.9994303584098816},
 {'label': 'neutral', 'score': 0.9996742010116577},
 {'label': 'neutral', 'score': 0.9995111227035522},
 {'label': 'neutral', 'score': 0.9997428059577942},
 {'label': 'neutral', 'score': 0.9997428059577942},
 {'label': 'positive', 'score': 0.6382704973220825},
 {'label': 'neutral', 'score': 0.999749481678009},
 {'label': 'neutral', 'score': 0.9853566288948059},
 {'label': 'neutral', 'score': 0.9470493793487549},
 {'label': 'neutral', 'score': 0.9994303584098816},
 {'label': 'neutral', 'score': 0.9997156262397766},
 {'label': 'neutral', 'score': 0.9992720484733582},
 {'label': 'neutral', 'score': 0.9989308714866638},
 {'label': 'neutral', 'score': 0.9993398785591125},
 {'label': 'neutral', 'score': 0.9954718351364136},
 {'label': 'neutral', 'score': 0.9994753003120422},
 {'label': 'neutral', 'score': 0.9964601397514343},
 {'label': 'neutral', 'score': 0.9877890944480896},
 {'label': 'neutral', 'score': 0.9997604489326477},
 {'label': 'neutral', 'score': 0.8321759104728699},
 {'label': 'neutral', 'score': 0.5987106561660767},
 {'label': 'neutral', 'score': 0.9995883107185364},
 {'label': 'neutral', 'score': 0.9996365308761597},
 {'label': 'neutral', 'score': 0.9994869232177734},
 {'label': 'neutral', 'score': 0.9507361054420471},
 {'label': 'neutral', 'score': 0.9995020627975464},
 {'label': 'neutral', 'score': 0.573352038860321},
 {'label': 'neutral', 'score': 0.9996557235717773},
 {'label': 'neutral', 'score': 0.9994839429855347},
 {'label': 'neutral', 'score': 0.9992181062698364},
 {'label': 'neutral', 'score': 0.9957962036132812},
 {'label': 'neutral', 'score': 0.9938536882400513},
 {'label': 'neutral', 'score': 0.999454915523529},
 {'label': 'neutral', 'score': 0.9988510608673096},
 {'label': 'neutral', 'score': 0.9983077049255371},
 {'label': 'positive', 'score': 0.9997877478599548},
 {'label': 'neutral', 'score': 0.9986215829849243},
 {'label': 'neutral', 'score': 0.9997552037239075},
 {'label': 'neutral', 'score': 0.9841324090957642},
 {'label': 'neutral', 'score': 0.9994625449180603},
 {'label': 'neutral', 'score': 0.6176875233650208},
 {'label': 'neutral', 'score': 0.9962456822395325},
 {'label': 'neutral', 'score': 0.9274189472198486},
 {'label': 'neutral', 'score': 0.9997739195823669},
 {'label': 'neutral', 'score': 0.9997159838676453},
 {'label': 'neutral', 'score': 0.9985389709472656},
 {'label': 'neutral', 'score': 0.9988343119621277},
 {'label': 'neutral', 'score': 0.9996668100357056},
 {'label': 'negative', 'score': 0.9921299815177917},
 {'label': 'neutral', 'score': 0.9997449517250061},
 {'label': 'neutral', 'score': 0.9990473389625549},
 {'label': 'neutral', 'score': 0.9996610879898071},
 {'label': 'neutral', 'score': 0.8268890380859375},
 {'label': 'neutral', 'score': 0.9953403472900391},
 {'label': 'neutral', 'score': 0.4971875548362732},
 {'label': 'neutral', 'score': 0.9994481205940247},
 {'label': 'neutral', 'score': 0.9971931576728821},
 {'label': 'positive', 'score': 0.9608845710754395},
 {'label': 'neutral', 'score': 0.9859160780906677},
 {'label': 'neutral', 'score': 0.9981087446212769},
 {'label': 'neutral', 'score': 0.9997674822807312},
 {'label': 'neutral', 'score': 0.9871648550033569},
 {'label': 'neutral', 'score': 0.9995689988136292},
 {'label': 'neutral', 'score': 0.9990624785423279},
 {'label': 'neutral', 'score': 0.9987300038337708},
 {'label': 'neutral', 'score': 0.9899291396141052},
 {'label': 'neutral', 'score': 0.9964085221290588},
 {'label': 'neutral', 'score': 0.9997467398643494},
 {'label': 'neutral', 'score': 0.9996473789215088},
 {'label': 'neutral', 'score': 0.9996860027313232},
 {'label': 'neutral', 'score': 0.9996473789215088},
 {'label': 'neutral', 'score': 0.9992740750312805},
 {'label': 'neutral', 'score': 0.9989834427833557},
 {'label': 'neutral', 'score': 0.9993972778320312},
 {'label': 'neutral', 'score': 0.9994633793830872},
 {'label': 'positive', 'score': 0.9998306035995483},
 {'label': 'neutral', 'score': 0.9709886908531189},
 {'label': 'neutral', 'score': 0.9992042183876038},
 {'label': 'neutral', 'score': 0.9992486834526062},
 {'label': 'neutral', 'score': 0.9994476437568665},
 {'label': 'neutral', 'score': 0.9985905289649963},
 {'label': 'positive', 'score': 0.9531803727149963},
 {'label': 'positive', 'score': 0.9997536540031433},
 {'label': 'neutral', 'score': 0.9996157884597778},
 {'label': 'positive', 'score': 0.9144974946975708},
 {'label': 'neutral', 'score': 0.9982798099517822},
 {'label': 'neutral', 'score': 0.9997974038124084},
 {'label': 'negative', 'score': 0.9960303902626038},
 {'label': 'neutral', 'score': 0.9981390237808228},
 {'label': 'neutral', 'score': 0.9996391534805298},
 {'label': 'neutral', 'score': 0.9995307922363281},
 {'label': 'neutral', 'score': 0.9996558427810669},
 {'label': 'neutral', 'score': 0.9992071986198425},
 {'label': 'neutral', 'score': 0.9520953297615051},
 {'label': 'neutral', 'score': 0.9991016387939453},
 {'label': 'neutral', 'score': 0.9988406300544739},
 {'label': 'neutral', 'score': 0.5220740437507629},
 {'label': 'neutral', 'score': 0.9974275231361389},
 {'label': 'negative', 'score': 0.8241208791732788},
 {'label': 'neutral', 'score': 0.9996501207351685},
 {'label': 'neutral', 'score': 0.999552309513092},
 {'label': 'neutral', 'score': 0.7757472991943359},
 {'label': 'neutral', 'score': 0.9995087385177612},
 {'label': 'neutral', 'score': 0.9990248680114746},
 {'label': 'neutral', 'score': 0.9997469782829285},
 {'label': 'neutral', 'score': 0.999108612537384},
 {'label': 'neutral', 'score': 0.999744713306427},
 {'label': 'neutral', 'score': 0.9996166229248047},
 {'label': 'neutral', 'score': 0.9992955923080444},
 {'label': 'negative', 'score': 0.9993119239807129},
 {'label': 'neutral', 'score': 0.9773828387260437},
 {'label': 'neutral', 'score': 0.9829917550086975},
 {'label': 'neutral', 'score': 0.9947052597999573},
 {'label': 'neutral', 'score': 0.9995948672294617},
 {'label': 'neutral', 'score': 0.9996077418327332},
 {'label': 'neutral', 'score': 0.9992820620536804},
 {'label': 'neutral', 'score': 0.9996707439422607},
 {'label': 'neutral', 'score': 0.9995816349983215},
 {'label': 'neutral', 'score': 0.5397969484329224},
 {'label': 'neutral', 'score': 0.9990886449813843},
 {'label': 'neutral', 'score': 0.9994250535964966},
 {'label': 'negative', 'score': 0.9991637468338013},
 {'label': 'neutral', 'score': 0.9992559552192688},
 {'label': 'neutral', 'score': 0.997351884841919},
 {'label': 'neutral', 'score': 0.9996341466903687},
 {'label': 'neutral', 'score': 0.9996938705444336},
 {'label': 'neutral', 'score': 0.9976611137390137},
 {'label': 'neutral', 'score': 0.99896240234375},
 {'label': 'neutral', 'score': 0.999403715133667},
 {'label': 'positive', 'score': 0.9965606331825256},
 {'label': 'neutral', 'score': 0.9991428852081299},
 {'label': 'neutral', 'score': 0.998701810836792},
 {'label': 'neutral', 'score': 0.9993215799331665},
 {'label': 'neutral', 'score': 0.8675450682640076},
 {'label': 'neutral', 'score': 0.9995821118354797},
 {'label': 'neutral', 'score': 0.9996117949485779},
 {'label': 'neutral', 'score': 0.9995831847190857},
 {'label': 'neutral', 'score': 0.9995747208595276},
 {'label': 'neutral', 'score': 0.9996769428253174},
 {'label': 'neutral', 'score': 0.9997212290763855},
 {'label': 'positive', 'score': 0.9920669794082642},
 {'label': 'neutral', 'score': 0.9995953440666199},
 {'label': 'neutral', 'score': 0.9997497200965881},
 {'label': 'neutral', 'score': 0.9923477172851562},
 {'label': 'neutral', 'score': 0.9978892207145691},
 {'label': 'positive', 'score': 0.5111673474311829},
 {'label': 'positive', 'score': 0.9997619986534119},
 {'label': 'neutral', 'score': 0.9997276663780212},
 {'label': 'neutral', 'score': 0.9504610896110535},
 {'label': 'positive', 'score': 0.9982104301452637},
 {'label': 'neutral', 'score': 0.9997256398200989},
 {'label': 'neutral', 'score': 0.9996309280395508},
 {'label': 'neutral', 'score': 0.9997792840003967},
 {'label': 'neutral', 'score': 0.9996395111083984},
 {'label': 'neutral', 'score': 0.9994388222694397},
 {'label': 'neutral', 'score': 0.9996222257614136},
 {'label': 'neutral', 'score': 0.9978204965591431},
 {'label': 'neutral', 'score': 0.9989864230155945},
 {'label': 'neutral', 'score': 0.9994547963142395},
 {'label': 'neutral', 'score': 0.999000608921051},
 {'label': 'neutral', 'score': 0.9995543360710144},
 {'label': 'positive', 'score': 0.9997674822807312},
 {'label': 'neutral', 'score': 0.9995489716529846},
 {'label': 'neutral', 'score': 0.9964656829833984},
 {'label': 'neutral', 'score': 0.9987177848815918},
 {'label': 'neutral', 'score': 0.9985112547874451},
 {'label': 'neutral', 'score': 0.9909761548042297},
 {'label': 'positive', 'score': 0.9994440674781799},
 {'label': 'neutral', 'score': 0.9993127584457397},
 {'label': 'neutral', 'score': 0.8604972958564758},
 {'label': 'negative', 'score': 0.987912118434906},
 {'label': 'neutral', 'score': 0.9995471835136414},
 {'label': 'neutral', 'score': 0.9985149502754211},
 {'label': 'neutral', 'score': 0.9479706287384033},
 {'label': 'neutral', 'score': 0.9997245669364929},
 {'label': 'neutral', 'score': 0.9995365142822266},
 {'label': 'positive', 'score': 0.6999996304512024},
 {'label': 'neutral', 'score': 0.9606725573539734},
 {'label': 'neutral', 'score': 0.9980456829071045},
 {'label': 'neutral', 'score': 0.993219792842865},
 {'label': 'neutral', 'score': 0.9897119998931885},
 {'label': 'neutral', 'score': 0.9990076422691345},
 {'label': 'neutral', 'score': 0.99898761510849},
 {'label': 'neutral', 'score': 0.7868350148200989},
 {'label': 'neutral', 'score': 0.999502420425415},
 {'label': 'neutral', 'score': 0.9995841383934021},
 {'label': 'neutral', 'score': 0.9983854293823242},
 {'label': 'neutral', 'score': 0.9843531250953674},
 {'label': 'neutral', 'score': 0.9997186064720154},
 {'label': 'neutral', 'score': 0.999554455280304},
 {'label': 'neutral', 'score': 0.9997581839561462},
 {'label': 'neutral', 'score': 0.9996861219406128},
 {'label': 'neutral', 'score': 0.9997274279594421},
 {'label': 'neutral', 'score': 0.9993607401847839},
 {'label': 'neutral', 'score': 0.9996895790100098},
 {'label': 'neutral', 'score': 0.9981582760810852},
 {'label': 'neutral', 'score': 0.9997219443321228},
 {'label': 'neutral', 'score': 0.9996992349624634},
 {'label': 'neutral', 'score': 0.9995928406715393},
 {'label': 'neutral', 'score': 0.9921855330467224},
 {'label': 'neutral', 'score': 0.9693670868873596},
 {'label': 'neutral', 'score': 0.9995695948600769},
 {'label': 'neutral', 'score': 0.9996252059936523},
 {'label': 'neutral', 'score': 0.9995306730270386},
 {'label': 'neutral', 'score': 0.9995964169502258},
 {'label': 'neutral', 'score': 0.9790118336677551},
 {'label': 'neutral', 'score': 0.9988273978233337},
 {'label': 'neutral', 'score': 0.9993600249290466},
 {'label': 'positive', 'score': 0.9910202622413635},
 {'label': 'neutral', 'score': 0.9988664388656616},
 {'label': 'neutral', 'score': 0.9992241859436035},
 {'label': 'neutral', 'score': 0.998563826084137},
 {'label': 'neutral', 'score': 0.9977622032165527},
 {'label': 'neutral', 'score': 0.9996787309646606},
 {'label': 'positive', 'score': 0.9956977367401123},
 {'label': 'neutral', 'score': 0.9998204112052917},
 {'label': 'neutral', 'score': 0.9996063113212585},
 {'label': 'positive', 'score': 0.9993712306022644},
 {'label': 'neutral', 'score': 0.999454915523529},
 {'label': 'neutral', 'score': 0.9997332692146301},
 {'label': 'neutral', 'score': 0.7726091742515564},
 {'label': 'neutral', 'score': 0.9996185302734375},
 {'label': 'neutral', 'score': 0.9997547268867493},
 {'label': 'neutral', 'score': 0.9990113973617554},
 {'label': 'neutral', 'score': 0.9996511936187744},
 {'label': 'neutral', 'score': 0.9996790885925293},
 {'label': 'neutral', 'score': 0.9995830655097961},
 {'label': 'positive', 'score': 0.5238193273544312},
 {'label': 'positive', 'score': 0.9951995611190796},
 {'label': 'neutral', 'score': 0.9996808767318726},
 {'label': 'neutral', 'score': 0.999731719493866},
 {'label': 'positive', 'score': 0.9177917242050171},
 {'label': 'positive', 'score': 0.995568573474884},
 {'label': 'positive', 'score': 0.9975256323814392},
 {'label': 'neutral', 'score': 0.9994781613349915},
 {'label': 'neutral', 'score': 0.9919392466545105},
 {'label': 'neutral', 'score': 0.9996261596679688},
 {'label': 'neutral', 'score': 0.9988940358161926},
 {'label': 'neutral', 'score': 0.9997144341468811},
 {'label': 'neutral', 'score': 0.9994297623634338},
 {'label': 'neutral', 'score': 0.985748827457428},
 {'label': 'positive', 'score': 0.9997979998588562},
 {'label': 'neutral', 'score': 0.9879260063171387},
 {'label': 'neutral', 'score': 0.9998193383216858},
 {'label': 'neutral', 'score': 0.9805150032043457},
 {'label': 'neutral', 'score': 0.9995902180671692},
 {'label': 'positive', 'score': 0.9965081810951233},
 {'label': 'neutral', 'score': 0.9789454340934753},
 {'label': 'neutral', 'score': 0.9994619488716125},

In [ ]:
df = pd.DataFrame(results)
df.rename(columns={"score":"sentiment_score"},inplace = True)
init = pd.concat([train,df],axis = 1)
init
init.to_csv(r'G:\Interview Projects\reddit\training\sentiment_initial_results.csv', index=False)

In [21]:
#loading results from local files
import pandas as pd
import numpy as np
init = pd.read_csv(r'G:\Interview Projects\reddit\training\sentiment_initial_results.csv')
init['label_value'] = np.where(init['label']=="positive",1,
                               np.where(init['label']=="neutral",0,-1))
init['year'] = pd.to_datetime(init['created_utc']).dt.year
init['month'] = pd.to_datetime(init['created_utc']).dt.month
init['quarter'] = 2
init.columns
init

,id,title,selftext,author,created_utc,score,num_comments,url,subreddit,upvote_ratio,...,surprise,surprisePercentage,window_start,window_end,label,sentiment_score,label_value,year,month,quarter
0,npgy6l,Caught a glimpse of AMC on its way to the moon!!,NaN,TheMarkIII,2021-06-01 00:05:19+00:00,1,1.0,https://i.redd.it/tuw6d5qlpj271.jpg,wallstreetbets,1.00,...,0.11,11.1111,2021-07-17,2021-08-16,neutral,0.990274,0,2021,6,2
1,nphcon,A pes M ake C ash! When this week is the quest...,NaN,ChuckLoner1980,2021-06-01 00:25:34+00:00,1,1.0,https://i.redd.it/3rg1kzm7tj271.jpg,wallstreetbets,1.00,...,0.11,11.1111,2021-07-17,2021-08-16,neutral,0.999554,0,2021,6,2
2,nphgfq,$180k on Discovery DISCA - Holding Strong for ...,NaN,BeWithoutCause,2021-06-01 00:31:05+00:00,28,108.0,https://www.reddit.com/gallery/nphgfq,wallstreetbets,0.57,...,0.11,11.1111,2021-07-17,2021-08-16,neutral,0.999673,0,2021,6,2
3,nphkm4,Shib is exploding right now. India unleashed c...,NaN,SellAndAvoidHell,2021-06-01 00:37:09+00:00,1,0.0,https://i.redd.it/iaf82iu9vj271.jpg,wallstreetbets,1.00,...,0.11,11.1111,2021-07-17,2021-08-16,neutral,0.986070,0,2021,6,2
4,nphl4v,I kept checking the sub and listening to retar...,NaN,ksegur,2021-06-01 00:37:59+00:00,1,1.0,https://i.redd.it/k70kaz8fvj271.jpg,wallstreetbets,1.00,...,0.11,11.1111,2021-07-17,2021-08-16,neutral,0.999342,0,2021,6,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45927,omvama,OPEC Deal is messing with me,"A very happy moment for us all, OPEC made a de...",wine_dine_and69,2021-07-18 17:38:31+00:00,72,96.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.87,...,0.11,6.8750,2021-06-30,2021-07-29,negative,0.983293,-1,2021,7,2
45928,opvvdq,$UAA DD Earning 08/03/2021,Under Armour \n\nTicker Symbol: $UAA\n\nCurren...,Proof_Sand_8277,2021-07-23 05:37:42+00:00,10,26.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.66,...,0.18,300.0000,2021-07-03,2021-08-02,neutral,0.995486,0,2021,7,2
45929,ot8wlv,Crying over your heavy $CRSR bags? Then this i...,"Alright retards, put down your peanutbutter an...",[deleted],2021-07-28 12:28:57+00:00,530,117.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.93,...,0.15,7.8125,2021-07-05,2021-08-04,neutral,0.999487,0,2021,7,2
45930,p0s8nu,Forget FAANG introducing the THICC ASS portfolio,https://preview.redd.it/ijdtc42xr8g71.png?widt...,rocksblocks88,2021-08-09 02:17:36+00:00,397,61.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.93,...,0.38,23.8994,2021-07-24,2021-08-23,neutral,0.999029,0,2021,8,2
45931,p5gb14,"$PAYA , payment processor with low IV","Hello, so I follow the [Kelly Criterion](https...",repos39,2021-08-16 13:42:04+00:00,553,216.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.97,...,0.38,23.8994,2021-07-24,2021-08-23,neutral,0.999036,0,2021,8,2

In [ ]:
# init['month'].drop_duplicates()

0       6
6160    7
8357    8
Name: month, dtype: int32

In [22]:
#merging with feature data
fts = pd.read_csv(r"G:\Interview Projects\reddit\data processing\otherfeatures.csv")
fts

train = pd.merge(init, fts, how = 'left', left_on = ['ticker','year','quarter'], right_on = ['tic','year','quarter'])
train

,id,title,selftext,author,created_utc,score,num_comments,url,subreddit,upvote_ratio,...,dltt_be,de_ratio,quick_ratio,cash_conversion,inv_turn,rect_turn,sale_invcap,sale_equity,sale_nwc,TICKER
0,npgy6l,Caught a glimpse of AMC on its way to the moon!!,NaN,TheMarkIII,2021-06-01 00:05:19+00:00,1,1.0,https://i.redd.it/tuw6d5qlpj271.jpg,wallstreetbets,1.00,...,0.500,1.016,1.710,121.071,3.286,5.634,0.797,1.195,3.131,A
1,nphcon,A pes M ake C ash! When this week is the quest...,NaN,ChuckLoner1980,2021-06-01 00:25:34+00:00,1,1.0,https://i.redd.it/3rg1kzm7tj271.jpg,wallstreetbets,1.00,...,0.500,1.016,1.710,121.071,3.286,5.634,0.797,1.195,3.131,A
2,nphgfq,$180k on Discovery DISCA - Holding Strong for ...,NaN,BeWithoutCause,2021-06-01 00:31:05+00:00,28,108.0,https://www.reddit.com/gallery/nphgfq,wallstreetbets,0.57,...,0.500,1.016,1.710,121.071,3.286,5.634,0.797,1.195,3.131,A
3,nphkm4,Shib is exploding right now. India unleashed c...,NaN,SellAndAvoidHell,2021-06-01 00:37:09+00:00,1,0.0,https://i.redd.it/iaf82iu9vj271.jpg,wallstreetbets,1.00,...,0.500,1.016,1.710,121.071,3.286,5.634,0.797,1.195,3.131,A
4,nphl4v,I kept checking the sub and listening to retar...,NaN,ksegur,2021-06-01 00:37:59+00:00,1,1.0,https://i.redd.it/k70kaz8fvj271.jpg,wallstreetbets,1.00,...,0.500,1.016,1.710,121.071,3.286,5.634,0.797,1.195,3.131,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45927,omvama,OPEC Deal is messing with me,"A very happy moment for us all, OPEC made a de...",wine_dine_and69,2021-07-18 17:38:31+00:00,72,96.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.87,...,0.261,0.748,0.916,18.959,13.590,8.737,0.562,0.724,25.740,CVX
45928,opvvdq,$UAA DD Earning 08/03/2021,Under Armour \n\nTicker Symbol: $UAA\n\nCurren...,Proof_Sand_8277,2021-07-23 05:37:42+00:00,10,26.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.66,...,1.167,2.125,1.477,115.349,2.278,7.278,1.397,3.029,2.855,UAA
45929,ot8wlv,Crying over your heavy $CRSR bags? Then this i...,"Alright retards, put down your peanutbutter an...",[deleted],2021-07-28 12:28:57+00:00,530,117.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.93,...,NaN,-16.897,0.796,132.208,2.548,6.317,1.539,NaN,10.213,MSI
45930,p0s8nu,Forget FAANG introducing the THICC ASS portfolio,https://preview.redd.it/ijdtc42xr8g71.png?widt...,rocksblocks88,2021-08-09 02:17:36+00:00,397,61.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.93,...,0.307,0.748,2.173,NaN,NaN,23.101,0.918,1.212,2.724,INTU
45931,p5gb14,"$PAYA , payment processor with low IV","Hello, so I follow the [Kelly Criterion](https...",repos39,2021-08-16 13:42:04+00:00,553,216.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.97,...,0.307,0.748,2.173,NaN,NaN,23.101,0.918,1.212,2.724,INTU

In [23]:
train.columns

Index(['id', 'title', 'selftext', 'author', 'created_utc', 'score',
       'num_comments', 'url', 'subreddit', 'upvote_ratio', 'ticker',
       'match_type', 'confidence', 'fiscalDateEnding', 'reportedDate',
       'reportedEPS', 'estimatedEPS', 'surprise', 'surprisePercentage',
       'window_start', 'window_end', 'label', 'sentiment_score', 'label_value',
       'year', 'month', 'quarter', 'costat', 'curcdq', 'datafmt', 'indfmt',
       'consol', 'tic', 'datadate', 'gvkey', 'ancq', 'atq', 'dlttq', 'oiadpq',
       'piq', 'revtq', 'wcapq', 'invchy', 'wcapcy', 'dvpspq', 'permno',
       'adate', 'qdate', 'public_date', 'dpr', 'npm', 'gpm', 'ptpm', 'roa',
       'roe', 'int_debt', 'debt_ebitda', 'cash_debt', 'dltt_be', 'de_ratio',
       'quick_ratio', 'cash_conversion', 'inv_turn', 'rect_turn',
       'sale_invcap', 'sale_equity', 'sale_nwc', 'TICKER'],
      dtype='object')

In [5]:
# init.sort_values(by = ['sentiment_score'])
# init[init['label']=="neutral"]

#用mean算是不是不太好？
res = init.groupby('ticker').agg({
    'label_value': 'mean',
    # 'label_value': lambda x: np.average(x, weights=init.loc[x.index, 'upvote_ratio']),
    'id': 'count'
}).reset_index().sort_values('id')

stks = pd.read_csv(r"G:\Interview Projects\reddit\data processing\stk-leveldata.csv")
stks

df = pd.merge(res[res['id']>=10], stks, on = 'ticker')

df['if_consistent'] = np.where((df['surprise']>0) & (df['label_value']>0), True, 
                               np.where((df['surprise']<0) & (df['label_value']<0),True,
                                        np.where((df['surprise']==0) & (df['label_value']==0),True,
                                                 False)))

# len(df[df['id']>10])
df

,ticker,label_value,id,fiscalDateEnding,reportedDate,reportedEPS,estimatedEPS,surprise,surprisePercentage,window_start,window_end,if_consistent
0,MSCI,-0.100000,10,2021-06-30,2021-07-27,2.45,2.30,0.15,6.5217,2021-06-27,2021-07-26,False
1,CRM,0.100000,10,2021-07-31,2021-08-25,1.48,0.93,0.55,59.1398,2021-07-25,2021-08-24,True
2,FANG,0.000000,10,2021-06-30,2021-08-02,2.40,2.19,0.21,9.5890,2021-07-02,2021-08-01,False
3,CF,0.100000,10,2021-06-30,2021-08-09,1.15,1.57,-0.42,-26.7516,2021-07-09,2021-08-08,False
4,DTE,0.000000,10,2021-06-30,2021-07-27,1.70,1.30,0.40,30.7692,2021-06-27,2021-07-26,False
...,...,...,...,...,...,...,...,...,...,...,...,...
84,T,0.037297,3271,2021-06-30,2021-07-22,0.89,0.80,0.09,11.2500,2021-06-22,2021-07-21,True
85,ARE,0.056201,3701,2021-06-30,2021-07-26,0.73,0.61,0.12,19.6721,2021-06-26,2021-07-25,True
86,ALL,0.052721,4116,2021-06-30,2021-08-04,3.79,3.17,0.62,19.5584,2021-07-04,2021-08-03,True
87,IT,0.075720,6392,2021-06-30,2021-08-03,2.24,1.73,0.51,29.4798,2021-07-03,2021-08-02,True
88,A,0.089249,9311,2021-07-31,2021-08-17,1.10,0.99,0.11,11.1111,2021-07-17,2021-08-16,True

In [ ]:
'''
Temporary feature combining
'''
#loading auxilary features
df1 = pd.read_csv(r"G:\Interview Projects\reddit\data collection\2019-2024 s&p matched non-ratios (WRDS).csv")
df2 = pd.read_csv(r"G:\Interview Projects\reddit\data collection\2019-2024 s&p matched ratios (WRDS).csv")
fts = pd.merge(df1, df2, left_on = ['tic','datadate'], right_on = ['TICKER', 'public_date'], how = 'left')

#creating a quarter index for auxilary feature matrix
fts['year'] = pd.to_datetime(fts['datadate']).dt.year
fts = fts.groupby(by = ["tic","year"]).apply(
    lambda x: x.sort_values("datadate").assign(quarter = range(1,len(x)+1))
).reset_index(drop=True)
#creating a quarter index for sentiment analysis feature matrix

# sample_train = pd.merge(df, )


fts

C:\Users\Anya Yuxin Li\AppData\Local\Temp\ipykernel_44896\460769924.py:11: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  fts = fts.groupby(by = ["tic","year"]).apply(

,costat,curcdq,datafmt,indfmt,consol,tic,datadate,gvkey,ancq,atq,...,quick_ratio,cash_conversion,inv_turn,rect_turn,sale_invcap,sale_equity,sale_nwc,TICKER,year,quarter
0,A,USD,STD,INDL,C,A,2019-01-31,126554,5240.0,8952.0,...,2.741,106.622,3.357,6.552,0.771,1.076,1.836,A,2019,1
1,A,USD,STD,INDL,C,A,2019-04-30,126554,5210.0,9022.0,...,2.851,114.186,3.311,6.443,0.768,1.062,1.796,A,2019,2
2,A,USD,STD,INDL,C,A,2019-07-31,126554,5168.0,8625.0,...,2.835,115.745,3.238,6.351,0.758,1.041,1.887,A,2019,3
3,A,USD,STD,INDL,C,A,2019-10-31,126554,6263.0,9452.0,...,2.441,115.980,3.242,6.200,0.778,1.045,2.073,A,2019,4
4,A,USD,STD,INDL,C,A,2020-01-31,126554,6399.0,9501.0,...,1.207,113.433,3.250,6.053,0.790,1.087,4.656,A,2020,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10949,A,USD,STD,INDL,C,ZTS,2023-12-31,13721,7943.0,14286.0,...,1.871,422.274,0.830,6.753,0.738,1.808,1.898,ZTS,2023,4
10950,A,USD,STD,INDL,C,ZTS,2024-03-31,13721,7989.0,14348.0,...,2.001,390.200,0.904,6.813,0.730,1.717,1.927,ZTS,2024,1
10951,A,USD,STD,INDL,C,ZTS,2024-06-30,13721,7963.0,14165.0,...,2.014,415.828,0.851,6.753,0.748,1.769,1.949,ZTS,2024,2
10952,A,USD,STD,INDL,C,ZTS,2024-09-30,13721,8075.0,14357.0,...,2.043,399.034,0.892,6.813,0.758,1.775,1.991,ZTS,2024,3
10953,A,USD,STD,INDL,C,ZTS,2024-12-31,13721,8251.0,14237.0,...,2.070,377.016,0.945,6.795,0.775,1.809,2.048,ZTS,2024,4